variables:
  UPSTREAM_REPO: mesa/drm

include:
  - project: 'wayland/ci-templates'
    ref: b7030c2cd0d6ccc5f6d4f8299bafa4daa9240d71
    file: '/templates/debian.yml'

stages:
  - container
  - build


# When & how to run the CI
.ci-run-policy:
  except:
    - schedules
  retry:
    max: 2
    when:
      - runner_system_failure

# CONTAINERS

.container:
  stage: container
  extends:
    - .ci-run-policy
  variables:
    DEBIAN_VERSION: buster-slim
    REPO_SUFFIX: $CI_JOB_NAME
    DEBIAN_EXEC: 'bash .gitlab-ci/container-${CI_JOB_NAME}.sh'
    # no need to pull the whole repo to build the container image
    GIT_STRATEGY: none

debian-x86_64:
  extends:
    - .debian@container-ifnot-exists
    - .container
  variables:
    DEBIAN_TAG: &debian_x86_64 "2019-11-16"
.use-debian-x86_64:
  variables:
    TAG: *debian_x86_64
  image: "$CI_REGISTRY_IMAGE/debian/debian-x86_64:$TAG"
  needs:
    - debian-x86_64

debian-arm64:
  extends:
    - .debian@container-ifnot-exists@arm64v8
    - .container
  variables:
    DEBIAN_TAG: &debian_arm64 "2020-01-23"
.use-debian-arm64:
  variables:
    TAG: *debian_arm64
  image: "$CI_REGISTRY_IMAGE/debian/debian-arm64:$TAG"
  needs:
    - debian-arm64


# BUILD

.meson-build:
  stage: build
  variables:
    GIT_DEPTH: 10
  script:
    - meson build
        -D amdgpu=true
        -D cairo-tests=true
        -D etnaviv=true
        -D exynos=true
        -D freedreno=true
        -D freedreno-kgsl=true
        -D intel=true
        -D libkms=true
        -D man-pages=true
        -D nouveau=true
        -D omap=true
        -D radeon=true
        -D tegra=true
        -D udev=true
        -D valgrind=auto
        -D vc4=true
        -D vmwgfx=true
        ${CROSS+--cross /cross_file-$CROSS.txt}
    - ninja -C build
    - ninja -C build test
    - DESTDIR=$PWD/install ninja -C build install
  artifacts:
    when: on_failure
    paths:
      - build/meson-logs/*

meson-x86_64:
  extends:
    - .ci-run-policy
    - .use-debian-x86_64
    - .meson-build

meson-i386:
  extends: meson-x86_64
  variables:
    CROSS: i386

meson-aarch64:
  extends:
    - .ci-run-policy
    - .use-debian-arm64
    - .meson-build
  tags:
    - aarch64

meson-armhf:
  extends: meson-aarch64
  variables:
    CROSS: armhf

meson-ppc64el:
  extends: meson-x86_64
  variables:
    CROSS: ppc64el

meson-arch-daily:
  rules:
    - if: '$SCHEDULE == "arch-daily"'
      when: on_success
    - when: never
  image: archlinux/base
  before_script:
    - pacman -Syu --noconfirm --needed
        base-devel
        cairo
        cunit
        docbook-xsl
        libatomic_ops
        libpciaccess
        libxslt
        meson
        valgrind
  extends: .meson-build
